#!/usr/bin/env bash
# Generated by fixmonorepo. Clones every repository and rebuilds the working tree.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dest="${1:-$here/ruined}"
if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 required (that is one dependency; you have $(grep -c '"name"' "$here/manifest.json") repositories)" >&2
  exit 1
fi
exec python3 "$here/fixmonorepo.py" ruin "$here" -o "$dest" "${@:2}"
